# Use root/example as user/password credentials
#removed container_name for users-mysql as we can not scale
#also need to remove port for scalling up
version: '2.2'

services:

  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    ports:
      - 2181:2181           #ZOOKEEPER
      - 3030:3030           #LANDOOP UI
      - 8081-8083:8081-8083 #REST PROXY, SCHEMA REGISTRY
      - 9581-9585:9581-9585 #JMX PORT
      - 9092:9092           #KAFKA BROKER
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      FORWARDLOGS: 0
      SAMPLEDATA: 0